baseURL = "/"
languageCode = "en-us"
title = "TensorFlow for R"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true

disqusShortname = "r-tensorflow"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
	# General information
	author = "J.J. Allaire"
	description = "Documentation for the TensorFlow for R interface"
	copyright = "Copyright 2019, RStudio, Inc."
	repo = "https://github.com/rstudio/tensorflow"

[[menu.main]]
	name   = "Home"
	url    = "/"
	identifier = "home-top"
	weight = 10
	
	
# Installation Menu

[[menu.main]]
	name   = "Installation"
	url    = "/installation/"
	identifier = "installation-top"
	parent = ""
	weight = 19

[[menu.main]]
  name = "Installing TensorFlow"
  url    = "/installation/"
  identifier = "installation-overview"
  parent = "installation-top"
  weight = 10
  
[[menu.main]]
  name = "Using a GPU"
  url    = "/installation/gpu"
  identifier = "installation-gpu"
  parent = "installation-top"
  weight = 20
	
# Tutorials

[[menu.main]]
	name   = "Tutorials"
	url    = "/tutorials/"
	identifier = "tutorials-top"
	weight = 20
	
[[menu.main]]
	name   = "Beginners"
	parent = "tutorials-top"
	weight = 21
	url = ""

[[menu.main]]
	name   = "Basic ML with Keras"
	parent = "tutorials-top"
	identifier = "tutorials-beginners-basic-ml-top"
	weight = 24
	url = "/tutorials/beginners/basic-ml/"
	
[[menu.main]]
	name   = "Load and preprocess data"
	parent = "tutorials-top"
	identifier = "tutorials-beginners-load-top"
	weight = 25
	url = "/tutorials/beginners/load/load_csv/"

[[menu.main]]
	name   = "Advanced"
	parent = "tutorials-top"
	weight = 50
	url = ""
	
[[menu.main]]
	name   = "Customization"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-customization-top"
	weight = 51
	url = "/tutorials/advanced/customization/tensors-operations/"

[[menu.main]]
	name   = "Images"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-images-top"
	weight = 52
	url = "/tutorials/advanced/images/cnn/"
	
[[menu.main]]
	name   = "Structured data"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-structured-top"
	weight = 53
	url = "/tutorials/advanced/structured/classify/"
	
[[menu.main]]
	name   = "Distributed training"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-distributed-top"
	weight = 54
	url = "/tutorials/advanced/distributed/distributed_training_with_keras/"

# Guides

[[menu.main]]
	name   = "Guide"
	url    = "/guide/"
	identifier = "guide-top"
	weight = 30
	

[[menu.main]]
	name   = "Keras"
	parent = "guide-top"
	weight = 21
	url = ""
	
[[menu.main]]
	name   = "Getting started"
	identifier = "keras-getting-started-top"
	parent = "guide-top"
	weight = 22
	url = "/guide/keras/"
	
[[menu.main]]
	name   = "Advanced"
	identifier = "keras-advanced-top"
	parent = "guide-top"
	weight = 23
	url = "/guide/keras/custom_layers/"
	
[[menu.main]]
	name   = "TensorFlow Mechanics"
	parent = "guide-top"
	weight = 30
	url = ""
	
[[menu.main]]
	name   = "Basics"
	parent = "guide-top"
	identifier = "custom-basic-top"
	weight = 31
	url = "/guide/tensorflow/eager_execution"
	
[[menu.main]]
	name   = "Advanced"
	parent = "guide-top"
	identifier = "custom-advanced-top"
	weight = 32
	url = "/guide/tensorflow/ragged_tensors"	
	
[[menu.main]]
	name   = "Data input pipeline"
	parent = "guide-top"
	weight = 40
	url = ""
	
[[menu.main]]
	name   = "Overview"
	parent = "guide-top"
	identifier = "data-overview-top"
	weight = 41
	url = "/guide/tfdatasets/introduction"

[[menu.main]]
	name   = "Feature spec API"
	parent = "guide-top"
	identifier = "data-feature-spec-top"
	weight = 42
	url = "/guide/tfdatasets/feature_spec"
	
[[menu.main]]
	name   = "TensorFlow Hub"
	parent = "guide-top"
	weight = 50
	url = ""

[[menu.main]]
	name   = "Basics"
	parent = "guide-top"
	identifier = "tfhub-basics-top"
	weight = 51
	url = "/guide/tfhub/intro"
	
[[menu.main]]
	name   = "Key concepts"
	parent = "guide-top"
	identifier = "tfhub-key-top"
	weight = 52
	url = "/guide/tfhub/key-concepts"
	
[[menu.main]]
	name   = "Model saving"
	parent = "guide-top"
	weight = 60
	url = ""	
	
[[menu.main]]
	name   = "Checkpoints"
	parent = "guide-top"
	identifier = "saving-checkpoint-top"
	weight = 61
	url = "/guide/saving/checkpoints"
	
[[menu.main]]
	name   = "Saved Model"
	parent = "guide-top"
	identifier = "saving-savedmodel-top"
	weight = 62
	url = "/guide/saving/saved_model"

# Deploy

[[menu.main]]
	name   = "Deploy"
	url    = "/deploy/"
	identifier = "deploy-top"
	weight = 60
	
[[menu.main]]
	name   = "Tools"
	url    = "/tools/"
	identifier = "tools-top"
	weight = 60
	
[[menu.main]]
	name   = "Training Runs"
	url    = "/tools/tfruns/"
	identifier = "tfruns-top"
	parent = "tools-top"
	weight = 10

[[menu.main]]
	name   = "Cloud ML"
	url    = "/tools/cloudml/"
	identifier = "cloudml-top"
	parent = "tools-top"
	weight = 20
	
[[menu.main]]
	name   = "API"
	url    = "/reference/keras"
	identifier = "reference-top"
	weight = 70

# Learn Navigational Menus

[[menu.main]]
	name   = "Learn"
	url    = "/learn/resources/"
	identifier = "learn-top"
	weight = 80	

# Blog Menu
	
[[menu.main]]
  name   = "Blog"
  url    = "/blog.html"
  identifier = "blog"
  weight = 90	
	

  

