baseURL = "/"
languageCode = "en-us"
title = "TensorFlow for R"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true

disqusShortname = "r-tensorflow"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
	# General information
	author = "J.J. Allaire"
	description = "Documentation for the TensorFlow for R interface"
	copyright = "Copyright 2017, RStudio, Inc."
	repo = "https://github.com/rstudio/tensorflow"

[[menu.main]]
	name   = "Home"
	url    = "/"
	identifier = "home-top"
	weight = 10
	
	
# Installation Menu

[[menu.main]]
	name   = "Installation"
	url    = "/installation/"
	identifier = "installation-top"
	parent = ""
	weight = 19

[[menu.main]]
  name = "Installing TensorFlow"
  url    = "/installation/"
  identifier = "installation-overview"
  parent = "installation-top"
  weight = 10
  
[[menu.main]]
  name = "Using a GPU"
  url    = "/installation/gpu"
  identifier = "installation-gpu"
  parent = "installation-top"
  weight = 20
	
# Tutorials

[[menu.main]]
	name   = "Tutorials"
	url    = "/tutorials/"
	identifier = "tutorials-top"
	weight = 20
	
[[menu.main]]
	name   = "Beginners"
	parent = "tutorials-top"
	weight = 21
	url = ""

[[menu.main]]
	name   = "Basic ML with Keras"
	parent = "tutorials-top"
	identifier = "tutorials-beginners-basic-ml-top"
	weight = 24
	url = "/tutorials/beginners/basic-ml/"
	
[[menu.main]]
	name   = "Load and preprocess data"
	parent = "tutorials-top"
	identifier = "tutorials-beginners-load-top"
	weight = 25
	url = "/tutorials/beginners/load/load_csv/"

[[menu.main]]
	name   = "Advanced"
	parent = "tutorials-top"
	weight = 50
	url = ""
	
[[menu.main]]
	name   = "Customization"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-customization-top"
	weight = 60
	url = "/tutorials/advanced/customization/tensors-operations/"

[[menu.main]]
	name   = "Images"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-images-top"
	weight = 60
	url = "/tutorials/advanced/images/cnn/"
	
[[menu.main]]
	name   = "Structured data"
	parent = "tutorials-top"
	identifier = "tutorials-advanced-structured-top"
	weight = 60
	url = "/tutorials/advanced/structured/classify/"

# Guides

[[menu.main]]
	name   = "Guide"
	url    = "/guide/"
	identifier = "guide-top"
	weight = 30
	
[[menu.main]]
	name   = "Keras"
	parent = "guide-top"
	weight = 21
	url = ""
	
[[menu.main]]
	name   = "Getting started"
	identifier = "keras-getting-started-top"
	parent = "guide-top"
	weight = 22
	url = "/guide/keras/guide_keras/"
	
[[menu.main]]
	name   = "Advanced"
	identifier = "keras-advanced-top"
	parent = "guide-top"
	weight = 23
	url = "/guide/keras/custom_layers/"
	
[[menu.main]]
	name   = "Examples"
	identifier = "keras-examples-top"
	parent = "guide-top"
	weight = 24
	url = "/guide/keras/examples/"
	
# Deploy

[[menu.main]]
	name   = "Deploy"
	url    = "/deploy/"
	identifier = "deploy-top"
	weight = 30


# Learn Navigational Menus

[[menu.main]]
	name   = "Learn"
	url    = "/learn/resources.html"
	identifier = "learn-top"
	weight = 60	

# Blog Menu
	
[[menu.main]]
  name   = "Blog"
  url    = "/blog.html"
  identifier = "blog"
  weight = 70	
	

  

