name: "Deploy to S3"

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: 'Build the webiste'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Hugo setup"
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: 0.58.3
      - name: "Hugo build"
        run: hugo --minify
      - name: "Deploy to S3"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'public'
      
